services:
  zot:
    image: zot
    build:
      context: src/docker
      dockerfile: zot.Dockerfile
    volumes:
      - ${PWD}/.volumes/zot-registry/:/var/lib/registry
    ports:
      - 5000:5000

  swank:
    image: cl-emacs-swank
    build:
      context: .
      dockerfile: src/docker/cl-emacs-swank.Dockerfile
    ports:
      - 4005:4005
    environment:
      - OCICL_REGISTRY=--plain-http zot:5000/ocicl
      - OCICL_GLOBALDIR=${PWD}/.volumes/cache-ocicl/
      - ASDF_DIR=${PWD}/.volumes/asdf/
    depends_on:
      - zot
    volumes:
      - .volumes/cache-common-lisp/:/root/.cache/common-lisp/
      - ${PWD}/.volumes/cache-ocicl/:${PWD}/.volumes/cache-ocicl/
      - ${PWD}/:${PWD}/
      - ${PWD}/../emacs/:${PWD}/../emacs/
    command: ["bash", "-c", "cd ${PWD}/ && echo '(sleep 1000000000000)' | ./run-swank.sh"]
